language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=4.0.5 WP_MULTISITE=0
    - WP_VERSION=4.0.5 WP_MULTISITE=1
    - WP_VERSION=4.1.5 WP_MULTISITE=0
    - WP_VERSION=4.1.5 WP_MULTISITE=1
    - WP_VERSION=4.2.2 WP_MULTISITE=0
    - WP_VERSION=4.2.2 WP_MULTISITE=1
    - WP_VERSION=4.2.10 WP_MULTISITE=0
    - WP_VERSION=4.2.10 WP_MULTISITE=1
    - WP_VERSION=4.3.1 WP_MULTISITE=0
    - WP_VERSION=4.3.1 WP_MULTISITE=1
    - WP_VERSION=4.3.6 WP_MULTISITE=0
    - WP_VERSION=4.3.6 WP_MULTISITE=1
    - WP_VERSION=4.4.1 WP_MULTISITE=0
    - WP_VERSION=4.4.1 WP_MULTISITE=1
    - WP_VERSION=4.4.5 WP_MULTISITE=0
    - WP_VERSION=4.4.5 WP_MULTISITE=1
    - WP_VERSION=4.5.1 WP_MULTISITE=0
    - WP_VERSION=4.5.4 WP_MULTISITE=1
    - WP_VERSION=4.6.1 WP_MULTISITE=0
    - WP_VERSION=4.6.1 WP_MULTISITE=1
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=1

before_install:
    - git submodule update --init --recursive
    - sleep 5

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

notifications:
    email:
        recipients:
          - aramzs@hacktext.com
        on_success: change
        on_failure: always
